name: Issue comment command
on:
  # https://help.github.com/en/articles/events-that-trigger-workflows#issue-comment-event-issue_comment
  issue_comment:
    types: [created, edited]

jobs:
  run:
    name: variant
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: variantdev/variant-action@v0.1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VARIANT_WORKING_DIR: "."
        VARIANT_COMMENT: "true"
      run: bash -c 'args=${{ github.event.issue_comment.body }}; args=${args#/}; /entrypoint.sh $args'
      if: startsWith(github.event.issue_comment.body, '/')
